# collin gros
# 12-12-2020
# cs484
# project-3
#
# makefile for project-3. compiles both server.c and client.c

all: server client

server: server.c
	gcc -g server.c -o server
client: client.c
	gcc -g client.c -o client

clean:
	rm -rf *.o server client
