run: main.o node.o graph.o search.o cc.o
	g++ -o run main.o node.o graph.o search.o cc.o
main.o: main.cpp
	g++ -c main.cpp
node.o: node.cpp
	g++ -c node.cpp
graph.o: graph.cpp
	g++ -c graph.cpp
search.o: search.cpp
	g++ -c search.cpp
cc.o: cc.cpp
	g++ -c cc.cpp
