run: main.o node.o graph.o search.o cc.o dijkstra.o list.o heap.o operations.o
	g++ -g -o run main.o node.o graph.o search.o cc.o dijkstra.o list.o heap.o operations.o
main.o: main.cpp
	g++ -g -c main.cpp
node.o: node.cpp
	g++ -g -c node.cpp
graph.o: graph.cpp
	g++ -g -c graph.cpp
search.o: search.cpp
	g++ -g -c search.cpp
cc.o: cc.cpp
	g++ -g -c cc.cpp
dijkstra.o: dijkstra.cpp
	g++ -g -c dijkstra.cpp
list.o: list.cpp
	g++ -g -c list.cpp
heap.o: heap.cpp
	g++ -g -c heap.cpp
operations.o: operations.cpp
	g++ -g -c operations.cpp
