# collin gros
# 11-03-2020
# cs474
# project2
#
# makefile for project 2
# compile with:
# 		make
# clean with:
#		clean


all:
	gcc main.c circ.h -lpthread -lrt -o run

clean:
	rm -f run
	rm -f *.o

